// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Pair
	Request
	Response
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pair struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Method string           `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path   string           `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Header map[string]*Pair `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Get    map[string]*Pair `protobuf:"bytes,4,rep,name=get" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Post   map[string]*Pair `protobuf:"bytes,5,rep,name=post" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body   string           `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Response struct {
	StatusCode int32            `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	Header     map[string]*Pair `protobuf:"bytes,2,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body       string           `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "Pair")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleClient interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type exampleClient struct {
	c           client.Client
	serviceName string
}

func NewExampleClient(serviceName string, c client.Client) ExampleClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "example"
	}
	return &exampleClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *exampleClient) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Example.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Example{hdlr}, opts...))
}

type Example struct {
	ExampleHandler
}

func (h *Example) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExampleHandler.Call(ctx, in, out)
}

// Client API for Foo service

type FooClient interface {
	Bar(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type fooClient struct {
	c           client.Client
	serviceName string
}

func NewFooClient(serviceName string, c client.Client) FooClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "foo"
	}
	return &fooClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *fooClient) Bar(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Foo.Bar", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Foo service

type FooHandler interface {
	Bar(context.Context, *Request, *Response) error
}

func RegisterFooHandler(s server.Server, hdlr FooHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Foo{hdlr}, opts...))
}

type Foo struct {
	FooHandler
}

func (h *Foo) Bar(ctx context.Context, in *Request, out *Response) error {
	return h.FooHandler.Bar(ctx, in, out)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x6f, 0x32, 0x49, 0xda, 0x9c, 0x6e, 0xee, 0x3d, 0x5c, 0x65, 0xa8, 0x7f, 0x28, 0x29,
	0x48, 0x16, 0x1a, 0x24, 0x6e, 0x44, 0x50, 0xc4, 0x52, 0x75, 0x59, 0xe6, 0x0d, 0xa6, 0xe4, 0x60,
	0x8b, 0x69, 0x27, 0x66, 0xa6, 0x62, 0x1f, 0xc0, 0xe7, 0xf1, 0x15, 0x25, 0xd3, 0x24, 0x74, 0x51,
	0x37, 0xc5, 0xdd, 0x99, 0x33, 0xbf, 0xef, 0xe4, 0x3b, 0x5f, 0x06, 0x42, 0x59, 0xcc, 0x93, 0xa2,
	0x54, 0x46, 0x45, 0x97, 0xe0, 0x4d, 0xe4, 0xbc, 0xc4, 0xbf, 0xc0, 0x5e, 0x69, 0xcd, 0x9d, 0x81,
	0x13, 0x87, 0xa2, 0x2a, 0xf1, 0x10, 0x82, 0x77, 0x99, 0xaf, 0x48, 0x73, 0x77, 0xc0, 0xe2, 0x50,
	0xd4, 0xa7, 0xe8, 0x93, 0x41, 0x47, 0xd0, 0xdb, 0x8a, 0xb4, 0xa9, 0x98, 0x05, 0x99, 0x99, 0xca,
	0x6a, 0x61, 0x7d, 0x42, 0x04, 0xaf, 0x90, 0x66, 0xc6, 0x5d, 0xdb, 0xb5, 0x35, 0x9e, 0x43, 0x30,
	0x23, 0x99, 0x51, 0xc9, 0xd9, 0x80, 0xc5, 0xbd, 0xf4, 0x7f, 0x52, 0x4f, 0x49, 0x9e, 0x6d, 0x7b,
	0xbc, 0x34, 0xe5, 0x5a, 0xd4, 0x0c, 0x0e, 0x81, 0xbd, 0x90, 0xe1, 0x9e, 0x45, 0xff, 0xb5, 0xe8,
	0x13, 0x99, 0x0d, 0x57, 0xdd, 0xe2, 0x19, 0x78, 0x85, 0xd2, 0x86, 0xfb, 0x96, 0xc2, 0x96, 0x9a,
	0x28, 0x5d, 0x63, 0xf6, 0xbe, 0xb2, 0x33, 0x55, 0xd9, 0x9a, 0x07, 0x1b, 0x3b, 0x55, 0xdd, 0xbf,
	0x87, 0xde, 0xd6, 0x77, 0x77, 0xec, 0x7f, 0x04, 0xbe, 0xdd, 0xd8, 0x2e, 0xd1, 0x4b, 0xfd, 0xa4,
	0xca, 0x49, 0x6c, 0x7a, 0x37, 0xee, 0xb5, 0xd3, 0xbf, 0x85, 0x6e, 0x63, 0x67, 0x1f, 0xf9, 0x1d,
	0x84, 0xad, 0xcf, 0x3d, 0xf4, 0xd1, 0x97, 0x03, 0x5d, 0x41, 0xba, 0x50, 0x4b, 0x4d, 0x78, 0x0a,
	0xa0, 0x8d, 0x34, 0x2b, 0x3d, 0x52, 0x19, 0xd9, 0x31, 0xbe, 0xd8, 0xea, 0xe0, 0x45, 0x1b, 0xbe,
	0x6b, 0xb3, 0x3a, 0x48, 0x1a, 0xe9, 0xce, 0xf4, 0x9b, 0xc0, 0xd8, 0x6f, 0x06, 0x96, 0xc6, 0xd0,
	0x19, 0x7f, 0xc8, 0x45, 0x91, 0x13, 0x9e, 0x80, 0x37, 0x92, 0x79, 0x8e, 0xdd, 0xe6, 0x9f, 0xf5,
	0xc3, 0xd6, 0x51, 0xf4, 0x27, 0x1d, 0x02, 0x7b, 0x54, 0x0a, 0x8f, 0x81, 0x3d, 0xc8, 0xf2, 0x07,
	0x68, 0x1a, 0xd8, 0x17, 0x7c, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xff, 0x90, 0x5c, 0x90, 0xce,
	0x02, 0x00, 0x00,
}
