client:
  peers:
    # peer0
    - host: "localhost"
      port: 7051
      eventHost: "localhost"
      eventPort: 7053
      primary: true
      tls:
        # Certificate location absolute path
        certificate: "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/docker-clis/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/cacerts/ca.org1.example.com-cert.pem"
        serverHostOverride: "peer0.org1.example.com"
  tls:
    enabled: true

  security:
    enabled: true
    hashAlgorithm: "SHA2"
    level: 256

  tcert:
    batch:
      size: 200

  orderer:
    host: "localhost"
    port: 7050
    tls:
      # Certificate localtion absolute path
      certificate: "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/docker-clis/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/cacerts/ca.example.com-cert.pem"
      serverHostOverride: "orderer.example.com"

  logging:
    level: info

  fabricCA:
    tlsEnabled: true
    id: "Org1MSP"
    name: "ca-org1"
    homeDir: "/tmp/"
    mspDir: "msp"
    serverURL: "https://localhost:7054"
    certfiles:
      - "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/docker-clis/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem"
    client:
      keyfile: "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/fabric-ca/client/msp/cacerts/localhost-7054.pem"
      certfile: "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/fabric-ca/client/msp/signcerts/cert.pem"

  cryptoconfig:
    path: "$GOPATH/src/github.com/CunTianXing/go_app/go-fabric/docker-clis/crypto-config"
